#!/bin/bash
sudo apt-get install php7.0
sudo apt-get install php7.0-dev
sudo apt-get install git gcc make re2c php7.0-dev php7.0-curl php7.0-mysql php7.0-json libpcre3-dev

git clone https://github.com/phalcon/zephir

cd zephir
./install -c

cd ..
zephir fullclean
zephir build

sudo touch /etc/php/7.0/cli/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php/7.0/cli/conf.d/part.ini"

sudo touch /etc/php/7.0/apache2/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php/7.0/apache2/conf.d/part.ini"

sudo touch /etc/php/7.0/fpm/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php/7.0/fpm/conf.d/part.ini"

cp /usr/bin/php /usr/bin/part
chmod +x /usr/bin/part
echo "Install completed, restart your webserver"