#!/bin/bash
sudo apt-get install php5
sudo apt-get install -y git gcc make re2c php5-dev php5-curl php5-mysql php5-json libpcre3-dev

git clone https://github.com/phalcon/zephir

cd zephir
./install -c

cd ..
zephir fullclean
zephir build

sudo rm /etc/php5/cli/conf.d/part.ini
sudo touch /etc/php5/cli/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php5/cli/conf.d/part.ini"

sudo mkdir /etc/part

sudo cp -r page /etc/part/page
sudo cp -r bin /etc/part/bin
sudo cp -r bin/part /usr/bin/part

sudo chmod +x /usr/bin/part

echo "Install completed"