#!/bin/bash
sudo apt-get install -y git gcc make re2c php5 php5-dev php5-curl php5-mysql php5-json libpcre3-dev

git clone https://github.com/phalcon/zephir

cd zephir
./install -c

cd ..
zephir build

sudo touch /etc/php5/cli/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php5/cli/conf.d/part.ini"

sudo touch /etc/php5/apache2/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php5/apache2/conf.d/part.ini"

sudo touch /etc/php5/fpm/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php5/fpm/conf.d/part.ini"

sudo sh -c "echo 'alias part=""php""' >> ~/.bash_aliases"

source ~/.bash_aliases
echo "Install completed, restart your webserver"