#!/bin/bash
sudo apt-get install php7.0
sudo apt-get install php7.0-dev
sudo apt-get install git gcc make re2c php7.0-dev php7.0-curl php7.0-mysql php7.0-json libpcre3-dev
git clone https://github.com/phalcon/zephir

cd zephir
./install -c

cd ..
zephir fullclean
zephir build

sudo rm /etc/php/7.0/cli/conf.d/part.ini
sudo touch /etc/php/7.0/cli/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php/7.0/cli/conf.d/part.ini"

sudo mkdir /etc/part

sudo cp page /etc/part/page
sudo cp bin /etc/part/bin
sudo cp bin/part /usr/bin/part

sudo chmod +x /usr/bin/part

echo "Install completed"