#!/bin/bash
sudo touch /etc/php5/cli/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php5/cli/conf.d/part.ini"

sudo touch /etc/php5/apache2/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php5/apache2/conf.d/part.ini"

sudo touch /etc/php5/fpm/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php5/fpm/conf.d/part.ini"

sudo sh -c "echo 'alias part=""php""' >> ~/.bash_aliases"

source ~/.bash_aliases
echo "Install completed, restart your webserver"