#!/bin/bash
sudo apt-get install -y git gcc make re2c php5 php5-dev php5-curl php5-mysql php5-json libpcre3-dev

git clone https://github.com/phalcon/zephir

cd zephir
./install -c

cd ..
zephir fullclean
zephir build

sudo touch /etc/php5/cli/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php5/cli/conf.d/part.ini"

sudo touch /etc/php5/apache2/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php5/apache2/conf.d/part.ini"

sudo touch /etc/php5/fpm/conf.d/part.ini
sudo sh -c "echo 'extension=part.so' >> /etc/php5/fpm/conf.d/part.ini"

sudo mkdir /etc/part
sudo mkdir /etc/part/bin

sudo cp bin/part-server.pp /etc/part/bin/part-server.pp
sudo cp main /usr/bin/part

sudo chmod +x /usr/bin/part

echo "Install completed, restart your webserver"